name = "axi-itinerary"
compatibility_date = "2024-09-17"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "axi-itinerary"
route = "axi-itinerary.app/*"

[env.staging]
name = "axi-itinerary-staging"

[[d1_databases]]
binding = "DB"
database_name = "axi-itinerary-db"
database_id = "fa91bed8-f5c5-4570-bf38-87994a1ce93c"

[vars]
ENVIRONMENT = "production"
