name = "axi-itinerary"
compatibility_date = "2024-09-17"
compatibility_flags = ["nodejs_compat"]
main = "frontend/.svelte-kit/cloudflare/_worker.js"

[assets]
directory = "frontend/.svelte-kit/cloudflare"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "axi-itinerary-db"
database_id = "807d36d2-1be9-4dea-a3ab-bf0637a91a27"
