name: CI

on:
  push:
    branches: [ main, 'copilot/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Use Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: |
          if ! command -v wasm-pack >/dev/null 2>&1; then
            cargo install wasm-pack
          fi

      - name: Install frontend deps
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Build wasm
        run: make build-wasm

      - name: Typecheck frontend
        working-directory: frontend
        run: pnpm run check

      - name: Build frontend
        working-directory: frontend
        run: pnpm run build

      - name: Backend tests
        working-directory: backend
        run: cargo test --all --quiet

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Build
        run: make build

      - name: Cloudflare Pages Deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler pages deploy frontend/.svelte-kit/cloudflare --project-name=axi-itinerary
